### PR TITLE
Fix reference field problem

### LINKED ISSUE #68: Fix problem with reference field
Fix problem with reference field and showing in web-page

### PR DESCRIPTION
**Pull request by Aarrtteemm123**
#68-fix reference field problem

### CODE REVIEW

File: admin/static/js/main.js [hunk 1]
```diff
@@ -14,8 +14,8 @@ $(document).ready(function () {
     });
 });
 
-window.setTimeout(function() {
-    $(".alert").fadeTo(500, 0, function (){
-      $(this)[0].style.display = 'none'
-    })
-}, 2000);
+//window.setTimeout(function() {
```
Comment (artempenteskul) [inline admin/static/js/main.js]: uncomment this function

**Review by artempenteskul — APPROVED** [review]

File: admin/app.py [hunk 2]
```diff
@@ -215,20 +227,20 @@ def uploadFiles():
 @app.route('/book-storage')
 @login_required
 def book_storage():
-    books = Book.objects()
+    books = Book.objects()[:10]
```
Comment (ivan-dubei) [inline admin/app.py]: Why do we limit objects that we show in the book storage ?

Comment (Aarrtteemm123) [reply admin/app.py]: Because we have too many books to show that all on page, it's a temporary solution in that task

**Review by ivan-dubei — APPROVED** [review]
